In [59]:
import pandas as pd
import numpy.random as ran
from numpy import max

In [61]:
dftrain = pd.read_csv('raw.csv')
numberClassA=df['target'].value_counts()[1]
total =len(df)
print(numberClassA)
print(total)
chance = float(160/250)
print(chance)

160
250
0.64

In [72]:
dftest = pd.read_csv('test.csv')
numberOfSamples =len(dftest)
print(numberOfSamples)
results = ran.binomial(1,chance,numberOfSamples)
resultIndex =range(total,(total+numberOfSamples))
print(max(resultIndex))
dfResults = pd.DataFrame(results,dtype =int)
dfResults.index = dfResults.index + total
dfResults.index.name ='id'
dfResults.columns=['target'] 
dfResults.to_csv('results.csv')

19750
19999

     0
0    0
1    0
2    1
3    0
4    1
5    1
6    0
7    1
8    1
9    0
10   1
11   0
12   1
13   1
14   0
15   1
16   1
17   0
18   1
19   0
20   1
21   1
22   1
23   0
24   0
25   1
26   1
27   1
28   1
29   1
..  ..
220  0
221  1
222  1
223  0
224  1
225  0
226  1
227  0
228  1
229  1
230  1
231  0
232  0
233  0
234  1
235  1
236  0
237  1
238  1
239  0
240  0
241  1
242  0
243  0
244  1
245  1
246  0
247  0
248  1
249  1

[250 rows x 1 columns]